version: '3.5'
services:
  develop:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: ubuntu-dev:18.04
    restart: always
    expose:
      - "22"
    ports:
      - "8022:22"
    volumes:
      - ~/Shin:/root/shin
      - ~/PycharmProjects:/root/project
      - ~/Workspace:/root/workspace
    stdin_open: true
    tty: true
